//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTB
    {
        public int ACCNO { get; set; }
        public string Accountholdername { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public Nullable<int> RefAccno { get; set; }
    }
}
