--create table CLIENT_MASTER(CLIENTNO VARCHAR(6) CHECK(CLIENTNO LIKE 'C%') PRIMARY KEY,NAME VARCHAR(20) NOT NULL,
--   ADDRESS1 VARCHAR(30),ADDRESS2 VARCHAR(30),CITY VARCHAR(15),PINCODE NUMERIC(8),STATE VARCHAR(15),BALDUE NUMERIC(10,2));
--SELECT * FROM CLIENT_MASTER;

--CREATE table PRODUCT_MASTER(PRODUCTNO VARCHAR(6) CHECK(PRODUCTNO LIKE 'P%') PRIMARY KEY,DESCRIPTION VARCHAR(15) NOT NULL,
--   PROFITPERC NUMERIC(4,2) NOT NULL,UNITMEASURE VARCHAR(10) NOT NULL,QTYONHAND NUMERIC(8) NOT NULL,REORDERLVL NUMERIC(8) NOT NULL,
--   SELLPRICE NUMERIC(8,2) NOT NULL,CONSTRAINT chk1 CHECK(SELLPRICE <> 0),COSTPRICE NUMERIC(8,2) NOT NULL,
--   CONSTRAINT chk2 CHECK(COSTPRICE <> 0));


--CREATE table SALESMAN_MASTER(SALESMANNO VARCHAR(6) CHECK(SALESMANNO LIKE 'S%')PRIMARY KEY,SALESMANNAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(30) NOT NULL,
--  ADDRESS2 VARCHAR(30),CITY VARCHAR(20),PINCODE NUMERIC(8),State VARCHAR(20),SALAMT NUMERIC(6,2) NOT NULL,CONSTRAINT chk3 CHECK(SALAMT <> 0),
--  TGTTOGET NUMERIC(6,2)NOT NULL,YTDSALES NUMERIC(6,2)NOT NULL,REMARKS VARCHAR(60));

--CREATE table SALES_ORDER(ORDERNO VARCHAR(6) CHECK(ORDERNO LIKE 'O%')PRIMARY KEY,CLIENTNO VARCHAR(6), FOREIGN KEY(CLIENTNO) REFERENCES CLIENT_MASTER(CLIENTNO),
-- ORDERDATE DATE,DELYADDR VARCHAR(25),SALESMANNO VARCHAR(6), FOREIGN KEY(SALESMANNO) REFERENCES SALESMAN_MASTER(SALESMANNO),DELYTYPE CHAR(1),
-- CONSTRAINT chk4 CHECK(DELYTYPE='P' OR DELYTYPE='F'),BILLEDYN CHAR(1),CONSTRAINT chk5 CHECK(BILLEDYN='Y' OR BILLEDYN='N'),DELYDATE DATE,
-- ORDERSTATUS VARCHAR(10),CONSTRAINT chk6 CHECK(ORDERSTATUS='In Process' OR ORDERSTATUS='Fulfilled' OR ORDERSTATUS='BACKORDER' OR ORDERSTATUS='Cancelled'));

--create table SALES_ORDER_DETAILS(ORDERNO VARCHAR(6),FOREIGN KEY(ORDERNO) REFERENCES SALES_ORDER(ORDERNO),PRODUCTNO VARCHAR(6),FOREIGN KEY
-- (PRODUCTNO) REFERENCES PRODUCT_MASTER(PRODUCTNO),QTYORDERED NUMERIC(8),QTYDISP NUMERIC(8),PRODUCTRATE NUMERIC(10,2),
-- primary key(ORDERNO,PRODUCTNO));

 --INSERT INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE) VALUES ('C00001', 'Ivan Bayross', 'Mumbai', 400054, 'Maharashtra', 15000); 
--INSERT INTO PRODUCT_MASTER VALUES ('P00001', 'T-Shirts', 5, 'Piece', 200, 50, 350, 250); 
--INSERT INTO SALESMAN_MASTER VALUES ('S00001', 'Aman', 'A/14', 'Worli', 'Mumbai', 400002, 'Maharashtra', 3000, 100, 50, 'Good'); 
--INSERT INTO SALES_ORDER (ORDERNO, ORDERDATE, CLIENTNO, DELYTYPE, BILLEDYN, SALESMANNO, DELYDATE, ORDERSTATUS) 
-- VALUES('O19001', '12-june-02', 'C00001', 'F', 'N', 'S00001', '20-july-02', 'In Process'); 
 --SELECT * FROM SALES_ORDER;
INSERT INTO SALES_ORDER_DETAILS (ORDERNO, PRODUCTNO, QTYORDERED, QTYDISP, PRODUCTRATE) VALUES('O19001', 'P00001', 4, 4, 525);
SELECT * FROM SALES_ORDER_DETAILS;

--SELECT NAME FROM CLIENT_MASTER;
--SELECT * FROM SALESMAN_MASTER;

--SELECT NAME FROM CLIENT_MASTER WHERE CITY='Mumbai';

--select DESCRIPTION FROM PRODUCT_MASTER WHERE SELLPRICE BETWEEN 2000 AND 5000;

--select NAME,CITY,STATE FROM CLIENT_MASTER WHERE STATE <> 'Maharashtra';

--select * from CLIENT_MASTER where CLIENTNO<>'C00003' AND CLIENTNO<>'C00002';

update PRODUCT_MASTER set SELLPRICE=1150.50 WHERE UNITMEASURE='1.44 DRIVE';

DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C00005';

SELECT NAME FROM CLIENT_MASTER WHERE CITY LIKE '_a%';

select COUNT(DESCRIPTION) FROM PRODUCT_MASTER WHERE SELLPRICE >= 1500;

SELECT QTYORDERED,QTYDISP FROM SALES_ORDER_DETAILS;   --10--

ALTER TABLE CLIENT_MASTER ADD PRIMARY KEY(CLIENTNO);

ALTER TABLE CLIENT_MASTER ADD PHONE_NO NUMERIC(10);

ALTER TABLE PRODUCT_MASTER ALTER COLUMN DESCRIPTION VARCHAR(15) NOT NULL;

alter table PRODUC_MASTER alter column PROFITPERC NUMERIC(4,2) not null;

alter table PRODUC_MASTER alter column SELLPRICE NUMERIC(8,2) not null;

alter table PRODUC_MASTER alter column COSTPRICE NUMERIC(8,2) not null;

ALTER TABLE CLIENT_MASTER ALTER COLUMN NAME VARCHAR(60);

ALTER TABLE CLIENT_MASTER DROP COLUMN PINCODE;







